### ISSUE TITLE
Update to 3.9.22 and set default value on wizard page

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-joomla#1]
https://github.com/joomla/joomla-cms/blob/staging/installation/configuration.php-dist

configuration.php-dist 修改成 configuration.php 

详情待研究

**Comment by chendelin1982** [comment]
configuration settings refer to: https://www.joomlashack.com/blog/joomla/guided-tour-your-joomla-configurationphp-file/

**Comment by qiaofeng1227** [comment]
Use configuration.php install must to solve the following two problems:
1. install joomla by multiple language(chinese and engilish)
2. install with simple data

**Comment by qiaofeng1227** [comment]
Install with wizard page, but there must be database info. by default in the page

**Comment by jiaosir-cn** [comment]
/data/wwwroot/joomla/installation/model/forms
修改database.xml 添加 default="xxxx" 就OK

**Comment by qiaofeng1227** [comment]
Done
