### ISSUE TITLE
Unable to display version

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-joomla#4]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [x] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
 "httpd  Server version: Apache/2.4.46 (IUS)",
        "mysql  Ver 14.14 Distrib 5.7.34, for Linux (x86_64) using  EditLine wrapper",
        "PHP 7.3.28 (cli) (built: Apr 27 2021 13:57:06) ( NTS )",
        "Docker version 20.10.6, build 370c289",
        "phpmyadmin version: \"version\": \"5.1.0\",",
        "Redis server v=5.0.9 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=8e71b781423942b2",
        "System version: CentOS 7.9",
        "Image name: joomla3.9.26-CentOS7.9"

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zengxc-1996** [comment]
tested OK on aliyun centos 7.x:
```
ok: [47.243.94.49] => {
    "end_check_versions.stdout_lines": [
        "httpd  Server version: Apache/2.4.46 (IUS)",
        "mysql  Ver 14.14 Distrib 5.7.34, for Linux (x86_64) using  EditLine wrapper",
        "PHP 7.3.28 (cli) (built: Apr 27 2021 13:57:06) ( NTS )",
        "Docker version 20.10.6, build 370c289",
        "phpmyadmin version: \"version\": \"5.1.0\",",
        "Redis server v=5.0.9 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=2e21f2d7123a4225",
        "joomla version: 3.9.26/",
        "System version: CentOS 7.9",
        "Image name: joomlazengxc-CentOS7.9"
```
