### ISSUE TITLE
英文文档中关于端口号的问题

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/ansible-joomla#5]
## Language

- [ ] Chinese
- [ ] English

## Content error

![image](https://user-images.githubusercontent.com/54173243/121119146-b3d43d00-c84d-11eb-946d-429cc9410463.png)

* URL: https://support.websoft9.com/docs/joomla/stack-components.html#ports
* Description: ansible项目中并未包含 ONLYOFFICE Document Server组件, 但英文文档中列出了该组件的端口。
* Screenshot

## Content optimization

1.除去8080端口。

* URL: https://support.websoft9.com/docs/joomla/stack-components.html#ports
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

中英文文档中，phpMyAdmin端口号9090是否应列出？

**Steps for the content**  

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
Done
