### ISSUE TITLE
joomla 4.0.3 can't open home page

### ISSUE THREAD

**Issue by hnczhjh** [Websoft9/ansible-joomla#6]
![image](https://user-images.githubusercontent.com/86603933/131325561-739ac458-f607-49be-b45a-9d1a1f89b333.png)

**Comment by hnczhjh** [comment]
#### joomla 3 have group.php files,but joomla 4 don't have group.php files 

joomla 3.9.26
![image](https://user-images.githubusercontent.com/86603933/131326254-f945909c-f51f-4be8-ae1b-ec1c40cadab6.png)

joomla 4.0.3
![image](https://user-images.githubusercontent.com/86603933/131325821-85d5ff18-63bf-4399-a830-6173488d8e53.png)

**Comment by qiaofeng1227** [comment]
you need to install by wizard
